### PR TITLE
nestopia-ue: add livecheckable

### PR DESCRIPTION
**Pull request by chenrui333**
# before the change

```
$ brew livecheck nestopia-ue
nestopia-ue (guessed) : 1.49 ==> 1.50
```

<details>
<summary>debug log</summary>

```
Trying with url https://github.com/rdanbrook/nestopia.git
Possible git repo detected at https://github.com/rdanbrook/nestopia.git
1.40-undead => #<Version:0x00007f97228e3b20 @version="1.40-undead", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 40>, #<Version::StringToken "undead">]>
1.41 => #<Version:0x00007f97228e3a58 @version="1.41", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 41>]>
1.42 => #<Version:0x00007f97228e3990 @version="1.42", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 42>]>
1.43 => #<Version:0x00007f97228e38a0 @version="1.43", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 43>]>
1.44 => #<Version:0x00007f97228e37d8 @version="1.44", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 44>]>
1.45 => #<Version:0x00007f97228e3710 @version="1.45", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 45>]>
1.46 => #<Version:0x00007f97228e3620 @version="1.46", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 46>]>
1.46.1 => #<Version:0x00007f97228e3558 @version="1.46.1", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 46>, #<Version::NumericToken 1>]>
1.46.2 => #<Version:0x00007f97228e3490 @version="1.46.2", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 46>, #<Version::NumericToken 2>]>
1.47 => #<Version:0x00007f97228e33a0 @version="1.47", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 47>]>
1.48 => #<Version:0x00007f97228e32d8 @version="1.48", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 48>]>
1.49 => #<Version:0x00007f97228e31e8 @version="1.49", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 49>]>
1.50 => #<Version:0x00007f97228e3120 @version="1.50", @tokens=[#<Version::NumericToken 1>, #<Version::NumericToken 50>]>
nestopia-ue (guessed) : 1.49 ==> 1.50
```

</details>

# after the change

```
$ brew livecheck nestopia-ue
nestopia-ue : 1.49 ==> 1.49
```

### CODE REVIEW

**Comment by chenrui333** [comment]
Yeah, they only did the source tag but there is no associated release artifact, I would say it is same to assume the sourceforge would be the source of truth. But we can certainly revisit this call.

**Comment by chenrui333** [comment]
I did add the information in the formula though.

**Comment by samford** [comment]
> I would say it is same to assume the sourceforge would be the source of truth

As mentioned, the upstream website points to the GitHub repo for the source archive (https://github.com/0ldsk00l/nestopia/archive/1.50.tar.gz), so to me it seems like the GitHub repo is more canonical at this point, especially since it also now has a release that SourceForge doesn't.

> I did add the information in the formula though.

If it's not clear, I'm referring to the archive `url` in the `nestopia-ue.rb` file in Homebrew/homebrew-core/Formula, not the livecheckable here. I don't see any related PRs in homebrew-core.

**Comment by samford** [comment]
Closing this as livecheck is finding the latest version correctly and the homebrew-core formula simply needs to be updated to version 1.50 (as mentioned previously).

**Pull request closed without merging**
