### PR TITLE
Fix livechecks that were failing due to redirects

### PR DESCRIPTION
**Pull request by jonhermansen**
Previously:

```
$ brew livecheck debianutils faac gegl kawa libraw zabbix
Error: redirection forbidden: http://packages.qa.debian.org/d/debianutils.html -> https://packages.qa.debian.org/d/debianutils.html
Error: Unable to get versions for Formulary::FormulaNamespaceafdf0b168bb554f617c6a05382917d22::Faac
Error: redirection forbidden: http://download.gimp.org/pub/gegl/0.3/ -> https://download.gimp.org/pub/gegl/0.3/
Error: Unable to get versions for Formulary::FormulaNamespace28c9c57e8cdb9123ac95e5757b37ba99::Kawa
Error: redirection forbidden: http://www.libraw.org/download/ -> https://www.libraw.org/download/
Error: redirection forbidden: http://www.zabbix.com/download -> https://www.zabbix.com/download
```

Now:

```
$ brew livecheck debianutils faac gegl kawa libraw zabbix
debianutils : 4.8.2 ==> 4.8.2
faac : 1.29.3 ==> 1.29.3
gegl : 0.3.18 ==> 0.3.18
kawa : 2.4 ==> 2.4
libraw : 0.18.2 ==> 0.18.2
zabbix : 3.2.7 ==> 3.2.7
```

I also slightly modified the faac regex.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@jonhermansen please rebase this when you have a chance since it's conflicted

**Comment by jonhermansen** [comment]
@ilovezfs Will do

**Comment by jonhermansen** [comment]
Hmm, I don't think I did that correctly 😭

**Comment by commitay** [comment]
```
$ brew livecheck debianutils faac gegl kawa libraw zabbix
debianutils : 4.8.4 ==> 4.8.4
faac : 1.29.9.2 ==> 1.29.9.2
gegl : 0.4.0 ==> 0.4.0
kawa : 3.0 ==> 3.0
libraw : 0.18.11 ==> 0.18.11
zabbix : 3.4.9 ==> 3.4.9
```

Closing this out as the livechecks have been fixed in other commits.

Thanks for the PR nonetheless @jonhermansen!

**Pull request closed without merging**
