### PR TITLE
Change `href=".*?/` to `href=.*?`

### PR DESCRIPTION
**Pull request by nandahkrishna**
This PR changes `href=".*?/` to `href=.*?`. It turns out the `/` (leading) wasn't required in any of the regexes, which I verified by comparing pre- and post-change debug outputs.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
The only 'exception' here is `pike`, where the entire prefix `/latest-stable/` was unnecessary (only the stable version is linked to on the homepage).

**Comment by nandahkrishna** [comment]
In the second commit (please excuse the message, didn't know what'd be ideal), I've made all the suggested changes and also converted the PyPI urls of those Livecheckables modified in this PR to `:stable`.

However `dq` fails because of a redirection error. Any idea on how to handle it @samford?

**Comment by samford** [comment]
> However qd fails because of a redirection error. Any idea on how to handle it @samford?

It sounds like you may need to run `brew update` to get the latest `qd` formula. I updated the URLs yesterday to avoid the previous redirections, so if you haven't updated since then you'll receive a redirection error when using `url :homepage`.

**Comment by nandahkrishna** [comment]
Haha, just realised it myself 😅

**Pull request merged**
