### PR TITLE
more livechecks 3

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@youtux when merging these, we should `rebase and merge` not `squash and merge`. I'm not sure if I can fix it now but we'll see.

**Comment by youtux** [comment]
Why is that?

**Comment by ilovezfs** [comment]
To preserve one commit per formula.

**Comment by youtux** [comment]
I see. We didn't really specify a workflow for this project, maybe it is better to document this.

**Pull request merged**
