### PR TITLE
anime-downloader: add livecheckable

### PR DESCRIPTION
**Pull request by nandahkrishna**
Adding Livecheckable for anime-downloader.

Do review and let me know if I should make any changes!

### CODE REVIEW

**Comment by dawidd6** [comment]
```
Error: anime-downloader: Unable to get versions
```

Doesn't seem to work.

**Comment by nandahkrishna** [comment]
Oh alright. Thought it'd be useful to have all formulae here, as I intend to take up the `livecheck` DSL issue. Let me know if I have to close this!

**Comment by dawidd6** [comment]
If a project is hosted on any known site (like Github, Gitlab or GNU) there is no need to create a dedicated livecheckable for it. Unless `brew livecheck` picks up `-rc` or other unwanted releases, which is not the case in this situation.

**Comment by nandahkrishna** [comment]
Alright, I'll keep that in mind. Thanks.

**Comment by samford** [comment]
@nandahkrishna If you would like to better understand how `livecheck` works, take a look at the code in the livecheck folder in this repo, especially [heuristic.rb](https://github.com/Homebrew/homebrew-livecheck/blob/master/livecheck/heuristic.rb).

`livecheck` handles a number of formulae automatically and we only add manual livechecks when the default behavior is inadequate.

**Comment by nandahkrishna** [comment]
Ah I see. I now understand what @dawidd6 was pointing out about the popular sites.

As I mentioned in #236 there are errors on using `livecheck` for some formulae, and I see that these are hosted on sites other than those included in heuristic.rb; I'll make PRs to try and fix those alone for now. 

Thanks @samford, that was insightful.

**Pull request closed without merging**
