### PR TITLE
Fixed "redirection forbidden" errors for pyqt and sip

### PR DESCRIPTION
**Pull request by aluttik**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@aluttik please make this one commit per formula :)

**Comment by aluttik** [comment]
@ilovezfs mb, I'll get on that later today

**Comment by aluttik** [comment]
@ilovezfs: Sorry that took so long, I totally forgot about this. Is that better?

**Comment by ilovezfs** [comment]
Thanks @aluttik! Shipped :)

**Pull request merged**
