### PR TITLE
ios-class-guard: skip as not maintained

### PR DESCRIPTION
**Pull request by chenrui333**
See README in https://github.com/Polidea/ios-class-guard

### CODE REVIEW

**Comment by SMillerDev** [comment]
I really don't think we should skip a check because there might not be more releases.

**Comment by chenrui333** [comment]
Yeah, another piece of information that I can add is the livecheck report is wrong at this moment.

```
$ brew livecheck ios-class-guard
ios-class-guard (guessed) : 0.8 ==> 3.5
```

I wonder if that would support this PR though.

**Comment by samford** [comment]
> I really don't think we should skip a check because there might not be more releases.

I agree in this case. Since we're able to check for versions, there isn't a good reason to skip this (e.g., if upstream starts making releases again, we would miss them). I generally reserve skipping for very exceptional circumstances (e.g., old, not being developed/maintained, _and_ there's no practical way for us to check for new versions).

**Comment by chenrui333** [comment]
Sounds good, closing it this PR then.

**Pull request closed without merging**
